name: "hkunetwork"

# Describe what the target network is/does.
description: "HKU EE SDP 2018 project by Allen Ngan 3035177034"

# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
version: 2

# The client section used by GO SDK.
client:
  # Which organization does this application instance belong to? The value must be the name of an org
  organization: HallA
  logging:
    level: info

  # Global configuration for peer, event service and orderer timeouts
  peer:
    timeout:
      connection: 3s
      queryResponse: 45s
      executeTxResponse: 30s
  eventService:
    timeout:
      connection: 3s
      registrationResponse: 3s
  orderer:
    timeout:
      connection: 3s
      response: 5s

  # Root of the MSP directories with keys and certs. The Membership Service Providers is component that aims to offer an abstraction of a membership operation architecture.
  cryptoconfig:
    path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config"

  # Some SDKs support pluggable KV stores, the properties under "credentialStore" are implementation specific
  credentialStore:
    path: "/tmp/allenapp-kvs"

     # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      path: "/tmp/allenapp-msp"

  # BCCSP config for the client. Used by GO SDK. It's the Blockchain Cryptographic Service Provider.
  # It offers the implementation of cryptographic standards and algorithms.
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

  tlsCerts:
    systemCertPool: false

# [Optional]. But most apps would have this section so that channel objects can be constructed based on the content below.
# If one of your application is creating channels, you might not use this
channels:
  hkuchannel:
    orderers:
      - orderer.hku.com

    # Network entity which maintains a ledger and runs chaincode containers in order to perform operations to the ledger. Peers are owned and maintained by members.
    peers:
      peer0.hallA.hku.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.hallA.hku.com:
      peer0.hallB.hku.com:
      peer1.hallB.hku.com:
  
  cuhkchannel:
    orderers:
      - orderer.hku.com
    peers:
      peer0.clubA.cuhk.com:
      peer1.clubA.cuhk.com:
      peer0.clubB.cuhk.com:
      peer1.clubB.cuhk.com:



# List of participating organizations in this network
organizations:
  HallA:
    mspid: HallAMSP
    cryptoPath: "peerOrganizations/hallA.hku.com/users/{userName}@hallA.hku.com/msp"
    peers:
      - peer0.hallA.hku.com
      - peer1.hallA.hku.com
    certificateAuthorities:
      - caA.hku.com

  HallB:
    mspid: HallBMSP
    cryptoPath: "peerOrganizations/hallB.hku.com/users/{userName}@hallB.hku.com/msp"
    peers:
      - peer0.hallB.hku.com
      - peer1.hallB.hku.com
    certificateAuthorities:
      - caB.hku.com

  ClubA:
    mspid: ClubAMSP
    cryptoPath: "peerOrganizations/clubA.cuhk.com/users/{userName}@clubA.cuhk.com/msp"
    peers:
      - peer0.clubA.cuhk.com
      - peer1.clubA.cuhk.com
    certificateAuthorities:
      - caA.cuhk.com

  ClubB:
    mspid: ClubBMSP
    cryptoPath: "peerOrganizations/clubB.cuhk.com/users/{userName}@clubB.cuhk.com/msp"
    peers:
      - peer0.clubB.cuhk.com
      - peer1.clubB.cuhk.com
    certificateAuthorities:
      - caB.cuhk.com

  OrdererOrg:
    mspid: OrdererMSP
    cryptoPath: "ordererOrganizations/hku.com/users/{userName}@hku.com/msp"

# List of orderers to send transaction and channel create/update requests to.
# The orderers consent on the order of transactions in a block to be committed to the ledger. For the time being only one orderer is needed.
orderers:
  orderer.hku.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.hku.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/ordererOrganizations/hku.com/tlsca/tlsca.hku.com-cert.pem"

# List of peers to send various requests to, including endorsement, query and event listener registration.
peers:
  peer0.hallA.hku.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:9051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:9053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.hallA.hku.com
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/peerOrganizations/hallA.hku.com/tlsca/tlsca.hallA.hku.com-cert.pem"

  peer1.hallA.hku.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:10051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:10053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer1.hallA.hku.com
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/peerOrganizations/hallA.hku.com/tlsca/tlsca.hallA.hku.com-cert.pem"

  peer0.hallB.hku.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:11051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:11053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.hallB.hku.com
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/peerOrganizations/hallB.hku.com/tlsca/tlsca.hallB.hku.com-cert.pem"

  peer1.hallB.hku.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:12051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:12053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer1.hallB.hku.com
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/peerOrganizations/hallB.hku.com/tlsca/tlsca.hallB.hku.com-cert.pem"

  peer0.clubA.cuhk.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:13051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:13053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.clubA.cuhk.com
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/peerOrganizations/clubA.cuhk.com/tlsca/tlsca.clubA.cuhk.com-cert.pem"

  peer0.clubB.cuhk.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:14051
    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:14053
    # These parameters should be set in coordination with the keepalive policy on the server
    grpcOptions:
      ssl-target-name-override: peer0.clubB.cuhk.com
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: "${GOPATH}/src/github.com/allen96/allenapp/fixtures/crypto-config/peerOrganizations/clubB.cuhk.com/tlsca/tlsca.clubB.cuhk.com-cert.pem"

# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows certificate management to be done via REST APIs.
certificateAuthorities:
  caA.hku.com:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: caA.hku.com

  caB.hku.com:
    url: https://localhost:8054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: caB.hku.com

  caA.cuhk.com:
    url: https://localhost:9054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: caA.cuhk.com

    caB.cuhk.com:
    url: https://localhost:9054
    # the properties specified under this object are passed to the 'http' client verbatim when making the request to the Fabric-CA server
    httpOptions:
      verify: false
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: caB.cuhk.com