# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#   Profile
################################################################################
Profiles:
    SixOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            CUHK:
                Organizations:
                    - *ClubA
                    - *ClubB
            HKU:
                Organizations:
                    - *HallA
                    - *HallB
    TwoOrgsChannel:
        Consortium: CUHK
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ClubA
                - *ClubB
    FourOrgsChannel:
        Consortium: HKU
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *HallA
                - *HallB
##########################
################################################################################
#   Section: Organizations
################################################################################
Organizations: 
    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/hku.com/msp
        AdminPrincipal: Role.ADMIN

    - &HallA
        Name: HallAMSP
        ID: HallAMSP
        MSPDir: crypto-config/peerOrganizations/hallA.hku.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: peer0.hallA.hku.com
            - Port: 7051

    - &HallB
        Name: HallBMSP
        ID: HallBMSP
        MSPDir: crypto-config/peerOrganizations/hallB.hku.com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            - Host: peer0.hallB.hku.com
            - Port: 7051            

    - &ClubA
        Name: ClubAMSP
        ID: ClubAMSP
        MSPDir: crypto-config/peerOrganizations/clubA.cuhk.com/msp
        AdminPrincipal: Role.ADMIN

    - &ClubB
        Name: ClubBMSP
        ID: ClubBMSP
        MSPDir: crypto-config/peerOrganizations/clubB.cuhk.com/msp
        AdminPrincipal: Role.MEMBER
                   
################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.hku.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
